# Generated by Django 2.2 on 2019-06-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WPworld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_world', models.CharField(max_length=200)),
                ('world_summary', models.CharField(max_length=200)),
                ('world_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'World',
            },
        ),
        migrations.CreateModel(
            name='WPseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('wp_world', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.WPworld', verbose_name='World')),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='WP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_title', models.CharField(max_length=200)),
                ('wp_content', models.TextField()),
                ('wp_published', models.DateTimeField(verbose_name='date published')),
                ('wp_slug', models.CharField(default=1, max_length=200)),
                ('wp_image', models.ImageField(blank=True, upload_to='images')),
                ('wp_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.WPseries', verbose_name='Series')),
            ],
        ),
    ]
